services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file:
      - ./.env
    environment:
      DB_URL: postgresql://${PGUSER}:${PGPASSWORD}@db:5432/${PGDATABASE}
      JWT_SECRET: ${JWT_SECRET}
      DAYS_A_VENCER: ${DAYS_A_VENCER}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    environment:
      VITE_API_URL: "http://backend:4000"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  dbdata:
